version: '3.4'

services:
  productsservice:
    image: productsservice
    build:
      context: ./ProductsService
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  ordersservice:
    image: ordersservice
    build:
      context: ./OrdersService
      dockerfile: Dockerfile
    ports:
      - "5001:80"